### ISSUE TITLE
Redirect /home to /

### ISSUE THREAD

**Issue by robalni** [red-eclipse/site#16]
Right now /home and / are two pages with the same content. I think it would be better to just have one of them and let the other one redirect to it.

**Comment by qreeves** [comment]
Actually, `/` is an alias for the internal label `home`.

**Comment by TheAssassin** [comment]
Well, he definitely has a point here. This is more about search engine optimization, and can easily be fixed in the `.htaccess`.
You call this "duplicate content problem" (read more about e.g. [here](https://moz.com/learn/seo/duplicate-content)).
I think we should internally rewrite `/` to `/bits/index.php?target=home`, and redirect `/home` to `/` using a separate `RewriteRule`.

**Comment by Hirato** [comment]
We could just add `<link href="http://www.redeclipse.net" rel="canonical" />` into the home page so the two get indexed at the same path.

**Comment by TheAssassin** [comment]
That would tell search engines to regard `http://www.redeclipse.net` as the primary resource, and could work. But not every SE provider has implemented this behaviour, I just know that Google have because they suggested the canonical links in RFC 6596.
The redirection strategy will work properly for every search engine.
It's up to you guys which approach you prefer.
